<?php include('includes/htmlfunc.inc.php'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name= "description" content="oasis printing is a print shop based in Hammersmith and Fulham, W6, London. we do lithography, and digital. we print full colour and two colour and Black on white. our telephone number is  0800 018 5512 or 020 7386 7755. our email is info@oasisprinting.com we print full colour business cards, leaflets, letterheads, brochures, wedding stationery, personal stationery, copying, compliment slips, invitations, newsletters, postcards, we do design, and typesetting, and have special offers. we are very cheap, and quick.you can order on line. we are very competitive. we take all major credit cards, visa, mastercard, American express. we are based in central London. we can deliver anywhere in the country, and delivery in central london. we can print same day digital business cards. we also print posters up to A0."/>
<meta name="keywords" content="" />
<link rel="stylesheet" title="Oasis default style sheet" type="text/css" href="css/oasisdefault.css" />
<title>Printers in Hammersmith & Fulham | Oasis Printing | Leaflets</title>
</head>
<body>
	<div id="holder">
		
		<?php DispNav('leaflets'); ?>
		
		<div id="main">
      <table class="sizes">
        <tr><td class="bold-large">130gsm paper</td><td>gloss/silk</td><td><a href="#130A4">A4 <span class="mini">(210x297mm)</span></a></td><td><a href="#130A5">A5 <span class="mini">(148.5x210mm)</span></a></td><td><a href="#130A6">A6 <span class="mini">(105x148.5mm)</span></a></td><td><a href="#13013A4">1/3rd A4 <span class="mini">(99x210mm)</span></a></td></tr>
        <tr><td class="bold-large">170gsm paper</td><td>gloss/silk</td><td><a href="#170A4">A4 <span class="mini">(210x297mm)</span></a></td><td><a href="#170A5">A5 <span class="mini">(148.5x210mm)</span></a></td><td><a href="#170A6">A6 <span class="mini">(105x148.5mm)</span></a></td><td><a href="#17013A4">1/3rd A4 <span class="mini">(99x210mm)</span></a></td></tr>	
        <tr><td class="bold-large">300gsm paper</td><td>gloss/silk</td><td><a href="#300A4">A4 <span class="mini">(210x297mm)</span></a></td><td><a href="#300A5">A5 <span class="mini">(148.5x210mm)</span></a></td><td><a href="#300A6">A6 <span class="mini">(105x210mm)</span></a></td><td><a href="#30013A4">1/3rd A4 <span class="mini">(99x210mm)</span></a></td></tr>
      </table>
      <p><h1 class="bold-massive">PRICES</h1></p>
      <div id="130A4">
        <p class="cost-title"><a name="130A4"></a><span class="bold-large">130gsm paper</span> gloss/silk</p>
        <table class="costs9">
          <tr class="tablehead"><td class="cost-indent">size</td><td>front</td><td>reverse</td><td class="costs-centered">500</td><td class="costs-centered">1,000</td><td class="costs-centered">2,000</td><td class="costs-centered">5,000</td><td class="costs-centered">10,000</td><td class="costs-centered">20,000</td></tr>
          <tr class="tablebody"><td>A4<br />&nbsp;<br /><span class="mini">(210x297mm)</span></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£60</td><td class="costs-border">£75</td><td class="costs-border">£120</td><td class="costs-border">£180</td><td class="costs-border">£280</td><td class="costs-border">£500</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td class="costs-border">£80</td><td class="costs-border">£95</td><td class="costs-border">£140</td><td class="costs-border">£200</td><td class="costs-border">£320</td><td class="costs-border">£580</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£98</td><td class="costs-border">£130</td><td class="costs-border">£165</td><td class="costs-border">£220</td><td class="costs-border">£320</td><td class="costs-border">£535</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td class="costs-border">£130</td><td class="costs-border">£150</td><td class="costs-border">£185</td><td class="costs-border">£280</td><td class="costs-border">£350</td><td class="costs-border">£600</td></tr>
          <tr><td></td><td colspan="7" class="costs-footer">zero rated for VAT<br />for further information or to order:<br /><span class="bold-large">020 7386 7755</span><br /><a href="mailto:info@oasisprinting.com?subject=Web%20enquiry&body=Company%20Name:%0A%0AContact%20name:%0A%0AContact%20Phone:%0A%0AEnquiry:">email</a><br /><span class="bold-large"><a href="designartwork.php" title="design/artwork">need design?</a></span></td></tr>
        </table>
      </div>
      <div id="130A5">
        <p class="cost-title"><a name="130A5"></a><span class="bold-large">130gsm paper</span> gloss/silk</p>
        <table class="costs9">
          <tr class="tablehead"><td class="cost-indent">size</td><td>front</td><td>reverse</td><td class="costs-centered">500</td><td class="costs-centered">1,000</td><td class="costs-centered">2,000</td><td class="costs-centered">5,000</td><td class="costs-centered">10,000</td><td class="costs-centered">20,000</td></tr>
          <tr class="tablebody"><td>A5<br />&nbsp;<br /><span class="mini">(148.5x210mm)</span></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£55</td><td class="costs-border">£70</td><td class="costs-border">£80</td><td class="costs-border">£130</td><td class="costs-border">£200</td><td class="costs-border">£300</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td class="costs-border">£70</td><td class="costs-border">£80</td><td class="costs-border">£90</td><td class="costs-border">£140</td><td class="costs-border">£235</td><td class="costs-border">£320</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£70</td><td class="costs-border">£80</td><td class="costs-border">£105</td><td class="costs-border">£150</td><td class="costs-border">£210</td><td class="costs-border">£395</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td class="costs-border">£95</td><td class="costs-border">£105</td><td class="costs-border">£125</td><td class="costs-border">£170</td><td class="costs-border">£265</td><td class="costs-border">£450</td></tr>
          <tr><td></td><td colspan="7" class="costs-footer">zero rated for VAT<br />for further information or to order:<br /><span class="bold-large">020 7386 7755</span><br /><a href="mailto:info@oasisprinting.com?subject=Web%20enquiry&body=Company%20Name:%0A%0AContact%20name:%0A%0AContact%20Phone:%0A%0AEnquiry:">email</a><br /><span class="bold-large"><a href="designartwork.php" title="design/artwork">need design?</a></span></td></tr>
        </table>
      </div>
      <div id="130A6">
        <p class="cost-title"><a name="130A6"></a><span class="bold-large">130gsm paper</span> gloss/silk</p>
        <table class="costs9">
          <tr class="tablehead"><td class="cost-indent">size</td><td>front</td><td>reverse</td><td class="costs-centered">500</td><td class="costs-centered">1,000</td><td class="costs-centered">2,000</td><td class="costs-centered">5,000</td><td class="costs-centered">10,000</td><td class="costs-centered">20,000</td></tr>
          <tr class="tablebody"><td>A6<br />&nbsp;<br /><span class="mini">(105x148.5mm)</span></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£42</td><td class="costs-border">£50</td><td class="costs-border">£65</td><td class="costs-border">£95</td><td class="costs-border">£120</td><td class="costs-border">£220</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td class="costs-border">£52</td><td class="costs-border">£60</td><td class="costs-border">£75</td><td class="costs-border">£105</td><td class="costs-border">£145</td><td class="costs-border">£260</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£65</td><td class="costs-border">£70</td><td class="costs-border">£80</td><td class="costs-border">£100</td><td class="costs-border">£125</td><td class="costs-border">£235</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td class="costs-border">£75</td><td class="costs-border">£85</td><td class="costs-border">£95</td><td class="costs-border">£120</td><td class="costs-border">£160</td><td class="costs-border">£280</td></tr>
          <tr><td></td><td colspan="7" class="costs-footer">zero rated for VAT<br />for further information or to order:<br /><span class="bold-large">020 7386 7755</span><br /><a href="mailto:info@oasisprinting.com?subject=Web%20enquiry&body=Company%20Name:%0A%0AContact%20name:%0A%0AContact%20Phone:%0A%0AEnquiry:">email</a><br /><span class="bold-large"><a href="designartwork.php" title="design/artwork">need design?</a></span></td></tr>
        </table>
      </div>
      <div id="13013A4">
        <p class="cost-title"><a name="13013A4"></a><span class="bold-large">130gsm paper</span> gloss/silk</p>
        <table class="costs9">
          <tr class="tablehead"><td class="cost-indent">size</td><td>front</td><td>reverse</td><td class="costs-centered">500</td><td class="costs-centered">1,000</td><td class="costs-centered">2,000</td><td class="costs-centered">5,000</td><td class="costs-centered">10,000</td><td class="costs-centered">20,000</td></tr>
          <tr class="tablebody"><td>1/3rd A4<br />&nbsp;<br /><span class="mini">(99x210mm)</span></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£50</td><td class="costs-border">£60</td><td class="costs-border">£80</td><td class="costs-border">£110</td><td class="costs-border">£180</td><td class="costs-border">£300</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td class="costs-border">£65</td><td class="costs-border">£75</td><td class="costs-border">£90</td><td class="costs-border">£135</td><td class="costs-border">£210</td><td class="costs-border">£330</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£75</td><td class="costs-border">£95</td><td class="costs-border">£120</td><td class="costs-border">£165</td><td class="costs-border">£210</td><td class="costs-border">£330</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td class="costs-border">£85</td><td class="costs-border">£110</td><td class="costs-border">£140</td><td class="costs-border">£185</td><td class="costs-border">£231</td><td class="costs-border">£380</td></tr>
          <tr><td></td><td colspan="7" class="costs-footer">zero rated for VAT<br />for further information or to order:<br /><span class="bold-large">020 7386 7755</span><br /><a href="mailto:info@oasisprinting.com?subject=Web%20enquiry&body=Company%20Name:%0A%0AContact%20name:%0A%0AContact%20Phone:%0A%0AEnquiry:">email</a><br /><span class="bold-large"><a href="designartwork.php" title="design/artwork">need design?</a></span></td></tr>
        </table>
      </div>
      <div id="170A4">
        <p class="cost-title"><a name="170A4"></a><span class="bold-large">170gsm paper</span> gloss/silk</p>
        <table class="costs9">
          <tr class="tablehead"><td class="cost-indent">size</td><td>front</td><td>reverse</td><td class="costs-centered">500</td><td class="costs-centered">1,000</td><td class="costs-centered">2,000</td><td class="costs-centered">5,000</td><td class="costs-centered">10,000</td><td class="costs-centered">20,000</td></tr>
          <tr class="tablebody"><td>A4<br />&nbsp;<br /><span class="mini">(210x297mm)</span></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£70</td><td class="costs-border">£85</td><td class="costs-border">£130</td><td class="costs-border">£215</td><td class="costs-border">£340</td><td class="costs-border">£550</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td class="costs-border">£90</td><td class="costs-border">£105</td><td class="costs-border">£150</td><td class="costs-border">£250</td><td class="costs-border">£370</td><td class="costs-border">£650</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£105</td><td class="costs-border">£135</td><td class="costs-border">£180</td><td class="costs-border">£245</td><td class="costs-border">£360</td><td class="costs-border">£595</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td class="costs-border">£140</td><td class="costs-border">£160</td><td class="costs-border">£200</td><td class="costs-border">£330</td><td class="costs-border">£396</td><td class="costs-border">£790</td></tr>
          <tr><td></td><td colspan="7" class="costs-footer">zero rated for VAT<br />for further information or to order:<br /><span class="bold-large">020 7386 7755</span><br /><a href="mailto:info@oasisprinting.com?subject=Web%20enquiry&body=Company%20Name:%0A%0AContact%20name:%0A%0AContact%20Phone:%0A%0AEnquiry:">email</a><br /><span class="bold-large"><a href="designartwork.php" title="design/artwork">need design?</a></span></td></tr>
        </table>
      </div>
      <div id="170A5">
        <p class="cost-title"><a name="170A5"></a><span class="bold-large">170gsm paper</span> gloss/silk</p>
        <table class="costs9">
          <tr class="tablehead"><td class="cost-indent">size</td><td>front</td><td>reverse</td><td class="costs-centered">500</td><td class="costs-centered">1,000</td><td class="costs-centered">2,000</td><td class="costs-centered">5,000</td><td class="costs-centered">10,000</td><td class="costs-centered">20,000</td></tr>
          <tr class="tablebody"><td>A5<br />&nbsp;<br /><span class="mini">(148.5x210mm)</span></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£58</td><td class="costs-border">£75</td><td class="costs-border">£85</td><td class="costs-border">£135</td><td class="costs-border">£205</td><td class="costs-border">£350</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td class="costs-border">£73</td><td class="costs-border">£85</td><td class="costs-border">£95</td><td class="costs-border">£145</td><td class="costs-border">£240</td><td class="costs-border">£385</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£75</td><td class="costs-border">£85</td><td class="costs-border">£115</td><td class="costs-border">£155</td><td class="costs-border">£220</td><td class="costs-border">£400</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td class="costs-border">£99</td><td class="costs-border">£110</td><td class="costs-border">£135</td><td class="costs-border">£210</td><td class="costs-border">£280</td><td class="costs-border">£460</td></tr>
          <tr><td></td><td colspan="7" class="costs-footer">zero rated for VAT<br />for further information or to order:<br /><span class="bold-large">020 7386 7755</span><br /><a href="mailto:info@oasisprinting.com?subject=Web%20enquiry&body=Company%20Name:%0A%0AContact%20name:%0A%0AContact%20Phone:%0A%0AEnquiry:">email</a><br /><span class="bold-large"><a href="designartwork.php" title="design/artwork">need design?</a></span></td></tr>
        </table>
      </div>
      <div id="170A6">
        <p class="cost-title"><a name="170A6"></a><span class="bold-large">170gsm paper</span> gloss/silk</p>
        <table class="costs9">
          <tr class="tablehead"><td class="cost-indent">size</td><td>front</td><td>reverse</td><td class="costs-centered">500</td><td class="costs-centered">1,000</td><td class="costs-centered">2,000</td><td class="costs-centered">5,000</td><td class="costs-centered">10,000</td><td class="costs-centered">20,000</td></tr>
          <tr class="tablebody"><td>A6<br />&nbsp;<br /><span class="mini">(105x148.5mm)</span></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£45</td><td class="costs-border">£53</td><td class="costs-border">£70</td><td class="costs-border">£100</td><td class="costs-border">£130</td><td class="costs-border">£230</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td class="costs-border">£57</td><td class="costs-border">£67</td><td class="costs-border">£80</td><td class="costs-border">£114</td><td class="costs-border">£180</td><td class="costs-border">£265</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£70</td><td class="costs-border">£75</td><td class="costs-border">£85</td><td class="costs-border">£115</td><td class="costs-border">£150</td><td class="costs-border">£250</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td class="costs-border">£80</td><td class="costs-border">£90</td><td class="costs-border">£100</td><td class="costs-border">£135</td><td class="costs-border">£180</td><td class="costs-border">£285</td></tr>
          <tr><td></td><td colspan="7" class="costs-footer">zero rated for VAT<br />for further information or to order:<br /><span class="bold-large">020 7386 7755</span><br /><a href="mailto:info@oasisprinting.com?subject=Web%20enquiry&body=Company%20Name:%0A%0AContact%20name:%0A%0AContact%20Phone:%0A%0AEnquiry:">email</a><br /><span class="bold-large"><a href="designartwork.php" title="design/artwork">need design?</a></span></td></tr>
        </table>
      </div>
      <div id="17013A4">
        <p class="cost-title"><a name="17013A4"></a><span class="bold-large">170gsm paper</span> gloss/silk</p>
        <table class="costs9">
          <tr class="tablehead"><td class="cost-indent">size</td><td>front</td><td>reverse</td><td class="costs-centered">500</td><td class="costs-centered">1,000</td><td class="costs-centered">2,000</td><td class="costs-centered">5,000</td><td class="costs-centered">10,000</td><td class="costs-centered">20,000</td></tr>
          <tr class="tablebody"><td>1/3rd A4<br />&nbsp;<br /><span class="mini">(99x210mm)</span></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£55</td><td class="costs-border">£65</td><td class="costs-border">£85</td><td class="costs-border">£115</td><td class="costs-border">£190</td><td class="costs-border">£310</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td class="costs-border">£59</td><td class="costs-border">£80</td><td class="costs-border">£95</td><td class="costs-border">£140</td><td class="costs-border">£220</td><td class="costs-border">£340</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£78</td><td class="costs-border">£99</td><td class="costs-border">£125</td><td class="costs-border">£165</td><td class="costs-border">£215</td><td class="costs-border">£335</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td class="costs-border">£90</td><td class="costs-border">£115</td><td class="costs-border">£145</td><td class="costs-border">£190</td><td class="costs-border">£240</td><td class="costs-border">£390</td></tr>
          <tr><td></td><td colspan="7" class="costs-footer">zero rated for VAT<br />for further information or to order:<br /><span class="bold-large">020 7386 7755</span><br /><a href="mailto:info@oasisprinting.com?subject=Web%20enquiry&body=Company%20Name:%0A%0AContact%20name:%0A%0AContact%20Phone:%0A%0AEnquiry:">email</a><br /><span class="bold-large"><a href="designartwork.php" title="design/artwork">need design?</a></span></td></tr>
        </table>
      </div>
      <div id="300A4">
        <p class="cost-title"><a name="300A4"></a><span class="bold-large">300gsm card</span> gloss/silk</p>
        <table class="costs9">
          <tr class="tablehead"><td class="cost-indent">size</td><td>front</td><td>reverse</td><td class="costs-centered">500</td><td class="costs-centered">1,000</td><td class="costs-centered">2,000</td><td class="costs-centered">5,000</td><td class="costs-centered">10,000</td><td class="costs-centered">20,000</td></tr>
          <tr class="tablebody"><td>A4<br />&nbsp;<br /><span class="mini">(210x297mm)</span></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£80</td><td class="costs-border">£120</td><td class="costs-border">£240</td><td class="costs-border">£385</td><td class="costs-border">£550</td><td class="costs-border">£1000</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td class="costs-border">£115</td><td class="costs-border">£135</td><td class="costs-border">£149</td><td class="costs-border">£415</td><td class="costs-border">£595</td><td class="costs-border">£1050</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£130</td><td class="costs-border">£170</td><td class="costs-border">£285</td><td class="costs-border">£400</td><td class="costs-border">£640</td><td class="costs-border">£1100</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td class="costs-border">£160</td><td class="costs-border">£200</td><td class="costs-border">£320</td><td class="costs-border">£450</td><td class="costs-border">£790</td><td class="costs-border">£1300</td></tr>
          <tr><td></td><td colspan="7" class="costs-footer">plus VAT<br />for further information or to order:<br /><span class="bold-large">020 7386 7755</span><br /><a href="mailto:info@oasisprinting.com?subject=Web%20enquiry&body=Company%20Name:%0A%0AContact%20name:%0A%0AContact%20Phone:%0A%0AEnquiry:">email</a><br /><span class="bold-large"><a href="designartwork.php" title="design/artwork">need design?</a></span></td></tr>
        </table>
      </div>
      <div id="300A5">
        <p class="cost-title"><a name="300A5"></a><span class="bold-large">300gsm card</span> gloss/silk</p>
        <table class="costs9">
          <tr class="tablehead"><td class="cost-indent">size</td><td>front</td><td>reverse</td><td class="costs-centered">500</td><td class="costs-centered">1,000</td><td class="costs-centered">2,000</td><td class="costs-centered">5,000</td><td class="costs-centered">10,000</td><td class="costs-centered">20,000</td></tr>
          <tr class="tablebody"><td>A5<br />&nbsp;<br /><span class="mini">(148.5x210mm)</span></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£70</td><td class="costs-border">£95</td><td class="costs-border">£125</td><td class="costs-border">£185</td><td class="costs-border">£325</td><td class="costs-border">£550</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td class="costs-border">£90</td><td class="costs-border">£105</td><td class="costs-border">£135</td><td class="costs-border">£195</td><td class="costs-border">£355</td><td class="costs-border">£600</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£85</td><td class="costs-border">£105</td><td class="costs-border">£150</td><td class="costs-border">£220</td><td class="costs-border">£350</td><td class="costs-border">£600</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td class="costs-border">£100</td><td class="costs-border">£125</td><td class="costs-border">£175</td><td class="costs-border">£285</td><td class="costs-border">£490</td><td class="costs-border">£680</td></tr>
          <tr><td></td><td colspan="7" class="costs-footer">plus VAT<br />for further information or to order:<br /><span class="bold-large">020 7386 7755</span><br /><a href="mailto:info@oasisprinting.com?subject=Web%20enquiry&body=Company%20Name:%0A%0AContact%20name:%0A%0AContact%20Phone:%0A%0AEnquiry:">email</a><br /><span class="bold-large"><a href="designartwork.php" title="design/artwork">need design?</a></span></td></tr>
        </table>
      </div>
      <div id="300A6">
        <p class="cost-title"><a name="300A6"></a><span class="bold-large">300gsm card</span> gloss/silk</p>
        <table class="costs9">
          <tr class="tablehead"><td class="cost-indent">size</td><td>front</td><td>reverse</td><td class="costs-centered">500</td><td class="costs-centered">1,000</td><td class="costs-centered">2,000</td><td class="costs-centered">5,000</td><td class="costs-centered">10,000</td><td class="costs-centered">20,000</td></tr>
          <tr class="tablebody"><td>A6<br />&nbsp;<br /><span class="mini">(105x148.5mm)</span></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£58</td><td class="costs-border">£80</td><td class="costs-border">£95</td><td class="costs-border">£165</td><td class="costs-border">£270</td><td class="costs-border">£365</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td class="costs-border">£80</td><td class="costs-border">£95</td><td class="costs-border">£125</td><td class="costs-border">£175</td><td class="costs-border">£290</td><td class="costs-border">£410</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£65</td><td class="costs-border">£87</td><td class="costs-border">£110</td><td class="costs-border">£180</td><td class="costs-border">£285</td><td class="costs-border">£385</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td class="costs-border">£90</td><td class="costs-border">£105</td><td class="costs-border">£140</td><td class="costs-border">£195</td><td class="costs-border">£315</td><td class="costs-border">£455</td></tr>
          <tr><td></td><td colspan="7" class="costs-footer">plus VAT<br />for further information or to order:<br /><span class="bold-large">020 7386 7755</span><br /><a href="mailto:info@oasisprinting.com?subject=Web%20enquiry&body=Company%20Name:%0A%0AContact%20name:%0A%0AContact%20Phone:%0A%0AEnquiry:">email</a><br /><span class="bold-large"><a href="designartwork.php" title="design/artwork">need design?</a></span></td></tr>
        </table>
      </div>
      <div id="30013A4">
        <p class="cost-title"><a name="30013A4"></a><span class="bold-large">300gsm card</span> gloss/silk</p>
        <table class="costs9">
          <tr class="tablehead"><td class="cost-indent">size</td><td>front</td><td>reverse</td><td class="costs-centered">500</td><td class="costs-centered">1,000</td><td class="costs-centered">2,000</td><td class="costs-centered">5,000</td><td class="costs-centered">10,000</td><td class="costs-centered">20,000</td></tr>
          <tr class="tablebody"><td>1/3rd A4<br />&nbsp;<br /><span class="mini">(99x210mm)</span></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£65</td><td class="costs-border">£90</td><td class="costs-border">£115</td><td class="costs-border">£175</td><td class="costs-border">£290</td><td class="costs-border">£410</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td><img src="images/Black.jpg" alt="Black on white" width="52" height="52" /></td><td class="costs-border">£85</td><td class="costs-border">£100</td><td class="costs-border">£130</td><td class="costs-border">£190</td><td class="costs-border">£330</td><td class="costs-border">£500</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/NoPrinting.jpg" alt="no printing" width="52" height="52" /></td><td class="costs-border">£75</td><td class="costs-border">£97</td><td class="costs-border">£125</td><td class="costs-border">£200</td><td class="costs-border">£300</td><td class="costs-border">£480</td></tr>
          <tr class="tablebody"><td></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td><img src="images/FullColour.jpg" alt="full colour" width="51" height="52" /></td><td class="costs-border">£95</td><td class="costs-border">£110</td><td class="costs-border">£160</td><td class="costs-border">£260</td><td class="costs-border">£360</td><td class="costs-border">£535</td></tr>
          <tr><td></td><td colspan="7" class="costs-footer">plus VAT<br />for further information or to order:<br /><span class="bold-large">020 7386 7755</span><br /><a href="mailto:info@oasisprinting.com?subject=Web%20enquiry&body=Company%20Name:%0A%0AContact%20name:%0A%0AContact%20Phone:%0A%0AEnquiry:">email</a><br /><span class="bold-large"><a href="designartwork.php" title="design/artwork">need design?</a></span></td></tr>
        </table>
      </div>
    </div>
  </div>
<?php DispFooter(); ?>